### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by bookvik** [mgiraldo/tenprintcover-py#2]
```
> python
Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> ./tenprintcover.py --title="Hello" --author="test" --cover ./cover.png
```

When I run it I got a blank white page. Help me dude!

**Comment by jenstroeger** [comment]
Try it with Python 3, that should work.

With Python 2 I can reproduce your problem, I'll take a look.

**Comment by jenstroeger** [comment]
Fixed with commit https://github.com/mgiraldo/tenprintcover-py/commit/c36209b5fa5bd2b5c7b040f17b937a65ab05eb63.
