### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by eshellman** [mgiraldo/tenprintcover-py#3]
We'd like to add this into https://github.com/gitenberg-dev/gitberg
Could you add a free license?

**Comment by jenstroeger** [comment]
I’ll leave this to @mgiraldo for now. Personally, I’ve got no problem with adding a free license; do you have a specific one in mind?

Do you plan to branch, or move this repo over completely?

**Comment by eshellman** [comment]
I'd like to include it in the gitberg package which is in pypi. gitberg is GPL, but any license is fine.

**Comment by jenstroeger** [comment]
[GPL 2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html) or [GPL 3](https://www.gnu.org/licenses/gpl-3.0.en.html)? @mgiraldo, if you have no objections, I’m happy to add a free license. (But since I’m the author of the original code, perhaps @mgiraldo wouldn’t care?)

**Comment by mgiraldo** [comment]
Whatever license you prefer is fine by me. Free license best? I tend to prefer MIT. Is MIT license good for you, @jenstroeger?

**Comment by mgiraldo** [comment]
i tend to prefer mit

**Comment by mgiraldo** [comment]
is mit license good for you, @jenstroeger ?

**Comment by jenstroeger** [comment]
I don’t know the finer differences between [MIT license](https://opensource.org/licenses/MIT) and GPL2/3. I’ll take a look...

**Comment by mgiraldo** [comment]
I think main difference being mit not requiring new code be contributed back 

but not sure

**Comment by eshellman** [comment]
MIT is good.

**Comment by jenstroeger** [comment]
@mgiraldo, you’re correct according to [this question](http://stackoverflow.com/questions/3902754/mit-vs-gpl-license).

I’m alright with [MIT](https://opensource.org/licenses/MIT) then. However, it would be nice to see useful improvements and fixes to the code become public though. @eshellman, would that be ok with you guys at [Gitenberg dev](https://github.com/gitenberg-dev)? What’s required to add the license, just a code comment?

Also, to avoid duplication, should we _move_ the entire `tenprintcover-py` repo over to Gitenberg, and discontinue the [original one](https://github.com/mgiraldo/tenprintcover-py)?

**Comment by eshellman** [comment]
@jenstroeger The code is potentially useful in projects not related to GITenberg, so better to keep it separate. I will add a PR for the code file so that it can included in other projects referencing this repo.
