### ISSUE TITLE
Missing exception support in Python 2

### ISSUE THREAD

**Issue by jenstroeger** [mgiraldo/tenprintcover-py#5]
Opening a file in Python 2

```python
try:
    with open(args.json_covers, "r") as f:
        ...
```
throws an [IOError](https://docs.python.org/2/library/exceptions.html#exceptions.IOError) exception which is not caught because [FileNotFoundError](https://docs.python.org/3/library/exceptions.html#FileNotFoundError) is a Python 3 exception. Add that exception to the exception list:

```python
except (FileNotFoundError, IOError):
```

**Comment by eshellman** [comment]
but FileNotFoundError = IOError. Did you try this?

**Comment by eshellman** [comment]
running this command:
`$ python tenprintcover.py --title=x --author=y --cover=fakedir/cover.png`
shows that the existing code works correctly.

**Comment by jenstroeger** [comment]
In Python 3, [FileNotFoundError](https://docs.python.org/3/library/exceptions.html#FileNotFoundError) is a subclass of [OSError](https://docs.python.org/3/library/exceptions.html#os-exceptions).

In Python 2, [OSError](https://docs.python.org/2.7/library/exceptions.html#exceptions.OSError) does exist but has no subclass FileNotFoundError, whereas [IOError](https://docs.python.org/2.7/library/exceptions.html#exceptions.IOError) is a “sibling” class of OSError (see [here](https://docs.python.org/2.7/library/exceptions.html#exception-hierarchy)).

Instead of assigning IOError to FileNotFoundError (and reaching across logical class hierarchies), I propose a proper subclassing like Python 3 implements it, although it’s not a functional implementation of that error class:
```python
_python_version, _, _, _ = sys.version_info
if _python_version == 2:
    class FileNotFoundError(OSError):
        pass
```
With that error class defined properly, `except` should be expanded as we discussed above.

Alternatively, we can broaden the `except` statements around `open()` to catch `OSError` instead of `FileNotFoundError` and that would work on both Py2 _and_ Py3:
```python
try:                                                                    
    with open(args.json_covers, "r") as f:                              
        ...
except OSError as e:                                               
    if e.errno == errno.ENOENT
        print("JSON cover file does not exist: " + args.json_covers)  
    else:
        # Print other error number.
```
At this point I would almost lean towards this solution as it is the simplest and cleanest one.

**Comment by eshellman** [comment]
I had not realized that different exceptions (IOError and OSError) are raised in Python 2 and 3. That's ugly. Now I understand why you don't like FileNotFoundError = OSError. That makes all the solutions hacky. I don't have the Py3 experience to know which is least bad, but I was thinking that FileNotFoundError = OSError at least confines the hackiness to Py2.

**Comment by jenstroeger** [comment]
Starting with Python 3.3, `IOError` was aliased with `OSError` (see [PEP 3151](https://www.python.org/dev/peps/pep-3151/)). If you look at the exception handling examples in the documentation for [Python 2](https://docs.python.org/2/tutorial/errors.html) and [Python 3](https://docs.python.org/3/tutorial/errors.html) then you can see how Python 2 uses `except IOError` and Python 3 uses `except OSError`to `open()` a file.

So perhaps our best chance to work with this difference is the following code:
```python
try:
    with open(args.json_covers, "r") as f:                              
        ...
except (IOError, OSError):
    print("File error something rather with file: " + args.json_covers)
```
This is a pretty wide range of errors to catch, not really my ideal approach (I prefer to catch _only_ exceptions that are being thrown) but considering that the script should be run by Py2 and Py3 interpreters, this is the best we can do?

**Comment by eshellman** [comment]
This is OK with me.

Maybe there is code for a FileNotFound exception that works the way it should. Perhaps in one of the 2/3 compatibility libraries, like compat or six or some other.

**Comment by jenstroeger** [comment]
The PEP 3151 that I mentioned above cleans up many issues that arose from the inconsistencies around `IOError` and `OSError`. I don’t think it’s worth the effort to try to implement a Py3.3+ style `FileNotFoundError` in the face of such inconsistencies.

I’ve just tested `except (OSError, IOError)` on Py2.6/7 and Py3.3/4/5 and it works just fine. Committed fix https://github.com/mgiraldo/tenprintcover-py/commit/7cc2fc19b4cee6928c5e012eed15462ffb1e46b2.
